
<style type="text/css">
	.small_logo {
		display: none;
	}
</style>
<div class="officialRulesContainer">
	
	<div class="flavorLogoImg">
		<img src="img/jj-flavor-logo.png">
	</div>

	<h2 class="officialRulesTitle">Official Rules</h2>
<div class="official-rules-text">
	<p><strong>JUICY JUICE<sup>&reg;</sup> “FLAVOR DISCOVERY” INSTANT WIN GAME FULL OFFICIAL RULES</strong></p>

	<p><strong>NO PURCHASE NECESSARY TO ENTER OR WIN. A PURCHASE WILL NOT INCREASE YOUR CHANCES OF WINNING. GAME SUBJECT TO ALL FEDERAL, STATE AND LOCAL LAWS AND REGULATIONS. VOID OUTSIDE THE U.S.A. AND WHERE PROHIBITED BY LAW.</strong></p>

	<p><strong>1. ELIGIBILITY: The Juicy Juice® “Flavor Discovery” Instant Win Game (the “Game”) is open to all legal residents of the 50 United States (including D.C.) who are 18 years of age or older or the age of majority in their jurisdiction of residence, whichever is greater, at time of participation</strong> (each an “Entrant”). Employees (and household or family members of such employees) of Harvest Hill Beverage Company (“Sponsor”) and its parents, affiliates, subsidiaries and advertising, promotion and fulfillment agencies, including the Administrator of this Game, and each of their affiliates are not eligible. Internet access is required to participate. Winning a prize is contingent on fulfilling all requirements set forth herein.</p>

	<p><strong>2. TO PLAY: </strong>Visit www.juicyjuice.com/flavordiscovery (“Web site”) beginning at 5:00 p.m. ET on February 5, 2018 through 11:59:59 p.m. ET on April 30, 2018 (the “Game Period”) and follow the onscreen instructions to spin the Game wheel to see if you are a potential winner. Data rates may apply to Game play on a mobile device. </p>

	<p><strong>3. GAME WINNER DETERMINATION: </strong>If your spin of the Game wheel lands on the “Winner” space, you are a potential winner. There will be one (1) prize available each day during the Game Period.  A “day” is defined as the 24-hour period beginning at Midnight ET on any individual calendar date during the Game Period and ending at 11:59:59 p.m. ET on that date, except on February 5, 2018 when the hours will be from 5 p.m. ET through 11:59:59 p.m. ET. The Web site will endeavor to notify entrants if the prize has been won for that day. Such notification may not be in real-time and entrants are encouraged to refresh their browser to see updates to the Web site.  If you land on any other space on the Game wheel, you will be invited to play a game, work a puzzle or complete an activity (collectively, “Activities”). Activities are for amusement only and have no impact on winner determination or prize award. All winners and Game plays are subject to verification and compliance with these Official Rules. You are not a winner until your eligibility and compliance with the Official Rules have been verified. The time of day when you play the Game, as recorded by the Game technology, will solely determine whether or not you are a potential winner. Game prizes are randomly time-seeded throughout the Game Period. A potential winner will be the first eligible person to play on or after the randomly selected time, subject to the prize limitations below. Prizes will be awarded in the order in which they become available in accordance with the Game technology. If multiple Game plays are received at exactly the same time, the Game technology will assign each a different or next-available, unused time. The computer clock of the Web site will be the official timekeeping device for this promotion.</p>

	<p><strong>4.	ENTRY LIMITATIONS: </strong>Entrants must have a valid e-mail address to participate. Each Entrant may use only one (1) e-mail address to participate in this Game, and such e-mail address may be used by only one person regardless of whether the e-mail address is shared by two or more people. No mass, automated or mechanically reproduced Game plays will be accepted. Any Entrant who uses more than one (1) e-mail address to participate in this Game may be disqualified and any prize won may be forfeited, subject to Sponsor’s sole discretion. If a dispute arises regarding who played the Game, the Game play will be deemed to be submitted by the Authorized Account Holder of the e-mail address used at the time of registration. “Authorized Account Holder” is defined as the natural person who is assigned an e-mail address by an Internet access provider, online service provider or other organization responsible for assigning e-mail addresses for the domain associated with the submitted e-mail address. All Game plays become the exclusive property of Sponsor and will not be returned or acknowledged. By participating in this Game, Entrants accept and agree to be bound by these Official Rules and the decisions of the judges, which shall be final, binding and conclusive on all matters.</p>

	<p><strong>5.	PRIZES: </strong>There will be eighty-five (85) prizes (one (1) per day of the Game Period), each consisting of a $40 pre-paid card. Approximate Retail Value (“ARV”) of all prizes: $3,400.00.</p>

	<p><strong>6.	ODDS: </strong>Odds of winning a daily prize depend on the total number of valid Game plays completed each day during the Game Period, and the date and time of such Game plays as recorded by the Game technology.</p>

	<p><strong>7.	PRIZE CONDITIONS: </strong>No substitution, assignment or transfer of prize shall be permitted, except at the sole discretion of Sponsor who reserves the right to substitute a prize with cash or another prize of comparable or greater value. Pre-paid cards are subject to all the terms, conditions and policies imposed by the issuer, as well as federal and state laws. Sponsor is not responsible for complaints or issues regarding pre-paid cards (i.e. issues with respect to activation, redemption, etc.) and winner should address any such concerns with the pre-paid card issuer. Prizes will be awarded “as is” with no warranty or guarantee, either expressed or implied, with respect to any prize. Each prizewinner is solely responsible for the payment of taxes to the relevant taxing authorities, including all federal, state and local income taxes, and any other taxes associated with the prize. Sponsor is not responsible for any winner’s inability or unwillingness to accept a prize, or for winner’s use or misuse of any prize accepted. All prize details are at Sponsor’s sole discretion. Any prizes depicted in promotional packaging, advertising materials, the Web site or otherwise in connection with this Game are for illustrative purposes only and may not represent the actual prizes that winner is awarded. By accepting a prize, each winner consents to the use of his/her name, city and state of residence, photographs, voice recordings and likenesses for publicity purposes in any and all media known or hereinafter invented, without territorial restriction, by Sponsor without additional compensation or permission, where permitted by law.</p>

	<p><strong>8.	PRIZE AWARD: </strong>Limit one (1) Prize per person/household. Upon receiving a winning notification, complete and submit the on-screen prize claim form to begin the verification process. Prize notifications and prize claim forms will not be emailed. Verification will occur and prizes will be awarded on monthly basis during the Game Period. Please allow 4 - 6 weeks for delivery of prizes following verification. All prizes will be delivered by mail to the mailing address provided by participant on the prize claim form. Sponsor is not responsible for any change of mailing address of participants. Potential winners may be required to complete an Affidavit of Eligibility and Release or any other documents requested by Sponsor as a condition of receiving a prize. All required documentation must be returned by the date specified in the notification or the prize will be forfeited. Prizes that are undeliverable will be forfeited and will not be awarded, unless otherwise determined by Sponsor. Unclaimed or unawarded prizes during the Game will not be awarded. </p>

	<p><strong>9.	RELEASE OF LIABILITY: </strong>Except where prohibited, by participating in the Game, each participant agrees to release and hold harmless the Sponsor, Administrator and their respective parents, subsidiaries and affiliated companies and officers, directors, employees, agents, licensees and assigns, and sponsors, advertisers, partners and agencies from and against any claim or cause of action arising out of participation in the Game or receipt or use of any prize, inc<strong>luding, but not limited to:</strong> (a) unauthorized human intervention in the Game; (b) technical errors, programming errors, transmission defaults or interruptions related to computers, software, servers, or telephone or network lines; (c) computer server failure and/or delayed, garbled or corrupted data transmitted by participants; (d) printing or typographical errors; (e) errors in the administration of the Game or the processing of entries/Game plays; (f) late, lost or undeliverable mail, e-mail or shipments; or (g) injury or damage to persons or property that may be caused, directly or indirectly, in whole or in part, from participant’s participation in the Game, or receipt or use of a prize.</p>

	<p><strong>10.	LIMITATION OF LIABILITY: </strong>Sponsor and Administrator are not responsible for (i) lost, late, misdirected or incomplete entries, whether caused by participant, printing errors or by any of the equipment or programming associated with or utilized in the Game; (ii) printing or typographical errors in any Game-related materials; and/or (iii) any computer, online, telephone, mail or technical malfunctions, delays or human errors that occur in the processing, transmission or receipt of Game plays or prize claim information, or for inaccurate transcription of entry information, or for entries that are stolen, misdirected, garbled, lost or delayed by computer/telephone transmissions, or any injury or damage to persons or property, including, but not limited to, participants’ computers, phones, hardware and/or software, which may be caused directly or indirectly, in whole or in part, from participants’ participation in the Game or receipt, redemption or use of any prize. Screenshots do not constitute proof a winning Game play or proof of delivery. Under no circumstances will more prizes than those set forth in these Official Rules be awarded. If a technical error, programming error, printing error, seeding error or the like occurs and results in more potential winners than available prizes for a particular prize level, Sponsor may elect to hold a random drawing from all eligible non-suspect claims received to award the indicated number of prizes for the prize in dispute.</p>
	 
	<p><strong>11.	SPECIAL GAME LIMITATION: </strong>If for any reason this Game is not capable of running as planned; or if this Game becomes corrupted or does not allow the proper administration of the Game and/or processing of entries/Game plays in accordance with these Official Rules for any reason; or if tampering, unauthorized intervention, actions by participants, fraud, technical or human failures, or any other causes, in the sole opinion of Sponsor, corrupts or affects the administration, security, fairness, integrity or proper conduct of this Game, Sponsor reserves the right, in its sole discretion, to disqualify any individual implicated in such action and/or to cancel, terminate, modify or suspend the Game, or any portion thereof, without obligation or to reject prize claims associated with such error or fraudulent action. Any Game play entry will be automatically void if it is determined to be a mass entry or mechanically reproduced, altered or tampered with in any way. In the event the Game is terminated prematurely, due to a computer programming, seeding, fraud, network or other error, Sponsor reserves the right to, but has no obligation to, award unclaimed prizes in a random drawing from among valid non-suspect eligible participants received up to the time of the impairment. Any attempts by an individual to access the Game via a bot script or other brute-force attack will result in that IP address becoming ineligible. Any attempt by a participant or any other individual to deliberately damage, interfere with, or undermine the legitimate operation of this Game is a violation of criminal and/or civil laws, and should such an attempt be made, Sponsor reserves the right to seek damages (including attorneys’ fees) and other remedies from any such person to the fullest extent permitted by law. Sponsor’s failure to enforce any term of these Official Rules shall not constitute a waiver of that provision.</p>

	<p><strong>12.	DISPUTES: </strong>Participants agree that all causes of action arising out of or connected with this Game, or any prize awarded, shall be resolved individually, without resort to any form of class action; and any and all claims, judgments and award shall be limited to actual out-of-pocket costs incurred, excluding attorneys’ fees and court costs. Participants agree that all issues and questions concerning the construction, validity, interpretation and enforceability of these Official Rules, participants' rights and obligations, or the rights and obligations of the Sponsor in connection with the Game, will be governed by, and construed in accordance with, the laws of the State of Connecticut, without giving effect to any choice of law or conflict of law rules. By entering, participants consent to the jurisdiction and venue of the federal, state and local courts located in Fairfield County, Connecticut.</p>

	<p><strong>13.	WINNERS LIST: </strong>For a list of winners, send a self-addressed, stamped envelope by April 30, 2018 to: Juicy Juice Flavor Discovery Game–WL, P.O. Box 7430, Wilton CT 06897-7430</p>

	<p><strong>14.	PRIVACY: </strong>By playing the Game, each participant agrees to Sponsor’s use of participant’s personal information as described in the Sponsor’s Privacy Policy, located at <a target="_blank" href="http://juicyjuice.com/privacy">http://juicyjuice.com/privacy </a></p>

	<p><strong>15.	SPONSOR: </strong>Harvest Hill Beverage Company, 1 High Ridge Park, Stamford, CT, 06905. </p>

	<p><strong>16.	ADMINISTRATOR: </strong>Epsilon Data Management, LLC, 10 Westport Rd., Wilton, CT 06897.</p>
</div>
</div>
